import type { Metadata } from "next";
import "./globals.css";
import { Jost } from "next/font/google";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/providers/provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen antialiased", jost.className)}>
        <Providers>
          {children}
        </Providers>
      </body>
      
    </html>
  );
}
