import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
export const metadata: Metadata = {
  title: "Mehul Parekh",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/images/images.ico" sizes="<generated>" />
      <body className={cn("min-h-screen antialiased", inter.className)}>
        <div className="min-h-screen px-12 md:px-32 lg:px-96 3xl:px-[36rem] py-16 text-zinc-100">
          <nav className="flex gap-4 mb-6 md:mb-3 font-display justify-start md:justify-end">
            <Link href={"/"} className="w-max cool-underline">
              home
            </Link>
            <Link href={"/projects"} className="w-max cool-underline">
              projects
            </Link>
            <Link href={"/about"} className="w-max cool-underline">
              about
            </Link>
            <Link
              href={
                "https://drive.google.com/file/d/1L_85ccTw_EbHqx1OYQNwSjv82oDMyMEY/view?usp=sharing"
              }
              target="_blank"
              className="flex gap-0.5 items-center w-max cool-underline"
            >
              resume <ArrowUpRight className="w-5 h-5" />
            </Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}

